[phases.setup]
<<<<<<< HEAD
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2"
=======
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT'
>>>>>>> dfb0b0a (add deployment configs)
